# Generated by Django 3.0.3 on 2020-12-25 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('khatabook', '0004_auto_20201212_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('phone', models.IntegerField(default=None, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='khatabook.PersonUser'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
