# Generated by Django 3.0.3 on 2020-12-25 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khatabook', '0005_auto_20201225_0713'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonUser',
            new_name='Person',
        ),
    ]
