# Generated by Django 3.0.3 on 2020-12-25 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khatabook', '0006_auto_20201225_0719'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
