# Generated by Django 3.0.3 on 2021-01-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatabook', '0009_auto_20210102_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
